remove interactive and tty

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -4,17 +4,29 @@
 # We'll use the current one (.githooks)
 hookDir="$(dirname $0)/../"
 
-# Specify the hooks you want to run during
-# the pre-commit process:
-# "$hookDir/areYouSure.sh"
+function hadolint() {
+	dockerfile=$1
+	echo "Executing hadolint against ${dockerfile} ..."
+	docker run --rm hadolint/hadolint < ${dockerfile}
+	if (($?)); then
+		echo "ERROR: hadolint: ${dockerfile}. Aborting commit"
+		exit 1
+	fi
+}
+
+function dockerfilelint() {
+	dockerfile=$1
+	echo "Executing dockerfile-lint against ${dockerfile} ..."
+	docker run --rm --privileged -v $PWD:/root/ projectatomic/dockerfile-lint dockerfile_lint -f ${dockerfile}
+	if (($?)); then
+		echo "ERROR: dockerfile-lint: ${dockerfile}. Aborting commit"
+		exit 1
+	fi
+}
+
 echo "Starting pre-commit validation sequence..."
-for i in *Dockerfile; do
-	echo "Executing hadolint against $i ..."
-	docker run --rm -i hadolint/hadolint < $i
-	echo "Executing dockerfile-lint against $i ..."
-	docker run -it --rm --privileged -v $PWD:/root/ projectatomic/dockerfile-lint dockerfile_lint -f $i
+for dockerfile in *Dockerfile; do
+	hadolint ${dockerfile}
+	dockerfilelint ${dockerfile}
 done
 
-if (($?)); then
-	echo "ERROR: something went wrong. Aborting commit"
-fi
